version: "3.8"
services:
  web:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./code:/code
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./code:/code